name: CI

on:
    pull_request:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: ibizaman
                  authToken: "${{ secrets.CACHIX_IBIZAMAN_AUTHTOKEN }}"
            - run: nix-build
            - uses: actions/upload-artifact@v2
              with:
                  name: uconfig
                  path: result/bin/uconfig
